export const prototypeCopyKeys = [
  'opportunity',
  'referralOpportunity',
  'firstAction',
  'future',
  'starterStation',
  'dragHint',
  'buyProduct',
  'placeStation',
  'moveStation',
  'validDrop',
  'invalidDrop',
  'invalidOpportunityDrop',
  'insufficientCash',
  'stationPlaced',
  'stationMoved',
  'delivered',
  'processing',
  'referralInMotion',
  'referralCreated',
  'prototypeComplete',
  'adjacencyBonus',
  'cash',
  'trust',
  'retry',
  'cancel',
] as const

export type PrototypeTextKey = (typeof prototypeCopyKeys)[number]
export type PrototypeLocale = 'en' | 'ar'

const copy: Record<PrototypeLocale, Record<PrototypeTextKey, string>> = {
  en: {
    opportunity: 'Customer opportunity',
    referralOpportunity: 'Customer referral',
    firstAction: 'Drag the +50 card to the turquoise Product station.',
    future: 'Later',
    starterStation: 'Product station',
    dragHint: 'Drag onto the turquoise Product station',
    buyProduct: 'Buy Product station',
    placeStation: 'Click an empty board cell to place the station',
    moveStation: 'Move station',
    validDrop: 'Looks good here',
    invalidDrop: 'Choose an open space',
    invalidOpportunityDrop: 'Drop onto a Product station',
    insufficientCash: 'Not enough cash',
    stationPlaced: 'Product station placed',
    stationMoved: 'Station moved',
    delivered: 'Opportunity delivered!',
    processing: 'Processing opportunity…',
    referralInMotion: 'Referral traveling from this station…',
    referralCreated: 'Referral arrived! Drag it to a Product station.',
    prototypeComplete: 'First chain complete. Try a different layout.',
    adjacencyBonus: 'Adjacent station bonus',
    cash: 'Cash',
    trust: 'Trust',
    retry: 'Try again',
    cancel: 'Cancel',
  },
  ar: {
    opportunity: 'فرصة عميل',
    referralOpportunity: 'إحالة عميل',
    firstAction: 'اسحب بطاقة +50 إلى محطة المنتج الفيروزية.',
    future: 'لاحقًا',
    starterStation: 'محطة المنتج',
    dragHint: 'اسحب إلى محطة المنتج الفيروزية',
    buyProduct: 'اشترِ محطة منتج',
    placeStation: 'انقر خلية فارغة في اللوحة لوضع المحطة',
    moveStation: 'حرّك المحطة',
    validDrop: 'المكان مناسب',
    invalidDrop: 'اختر مساحة خالية',
    invalidOpportunityDrop: 'أسقط على محطة منتج',
    insufficientCash: 'النقد غير كافٍ',
    stationPlaced: 'وُضعت محطة المنتج',
    stationMoved: 'نُقلت المحطة',
    delivered: 'تم تسليم الفرصة!',
    processing: 'جاري تنفيذ الفرصة…',
    referralInMotion: 'إحالة تنطلق من هذه المحطة…',
    referralCreated: 'وصلت الإحالة! اسحبها إلى محطة منتج.',
    prototypeComplete: 'اكتملت السلسلة الأولى. جرّب ترتيبًا مختلفًا.',
    adjacencyBonus: 'مكافأة المحطات المتجاورة',
    cash: 'النقد',
    trust: 'الثقة',
    retry: 'حاول مجددًا',
    cancel: 'إلغاء',
  },
}

export function prototypeText<K extends PrototypeTextKey>(
  locale: PrototypeLocale,
  key: K,
): (typeof copy)[PrototypeLocale][K] {
  return copy[locale][key]
}
